version: "3.8"

# configure services
services:

    # PHP 8.0.10 container with apache 2.4
    # https://hub.docker.com/repository/docker/ixnode/php
    apache:
        image: 'ixnode/php:8.0.10-apache'
        container_name: 'de.ixno.php-json-beautifier-0.0.1-apache'
        hostname: 'de.ixno.php-json-beautifier-0.0.1-apache'
        restart: always
        ports:
            - 8021:80
        volumes:
            - ./:/var/www/html/:delegated
        networks:
            - network-internal

    # PHP 8.0.10 cli container
    # https://hub.docker.com/repository/docker/ixnode/php
    php:
        image: 'ixnode/php:8.0.10-cli'
        container_name: 'de.ixno.php-json-beautifier-0.0.1-cli'
        hostname: 'de.ixno.php-json-beautifier-0.0.1-cli'
        restart: always
        command: "cron -f"
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html/
        networks:
            - network-internal

    # https://hub.docker.com/_/composer
    # Composer 2.1.6
    #
    # Show composer version:
    # ----------------------
    # $ docker-compose run --rm composer -V
    #
    # Composer install:
    # -----------------
    # $ docker-compose run --rm composer install
    #
    # Run tests:
    # ----------
    # $ docker-compose run --rm composer test
    #
    # Show PHP version:
    # -----------------
    # $ docker-compose run --rm composer php-version
    composer:
        image: 'composer:2.1.6'
        container_name: 'de.ixno.php-json-beautifier-0.0.1-composer'
        hostname: 'de.ixno.php-json-beautifier-0.0.1-composer'
        volumes:
            - $PWD:/app
        user: "${UID}:${GID}"
        networks:
            - network-internal

# configure networks
networks:
    network-internal:
        external: false
        name: 'de.ixno.php-json-beautifier-network'
